# Group 22
# Samay Gandhi 2020A7PS0299P
# Mohit Makwana 2020A7PS0048P
# Kathan Patel 2020A7PS0058P
# Aditya Sheth 2020A7PS1511P
# Aryan Chavan 2020A7PS1692P

target:
	 gcc driver.c -o compiler
	 @echo "Run command: ./compiler <testfile> <file_name_to_store_parse_tree> <buffer_size>"
	 @echo "Run 'make test' for running testcases"

test:
	 gcc driver.c -o compiler
	./compiler testcase1.txt parse_tree.txt 100
	./compiler testcase2.txt parse_tree.txt 100
	./compiler testcase3.txt parse_tree.txt 100
	./compiler testcase4.txt parse_tree.txt 100
	./compiler testcase5.txt parse_tree.txt 100
	./compiler testcase6.txt parse_tree.txt 100
	./compiler testcase7.txt parse_tree.txt 100
	./compiler testcase8.txt parse_tree.txt 100
	./compiler testcase9.txt parse_tree.txt 100
	./compiler testcase10.txt parse_tree.txt 100
	./compiler testcase11.txt parse_tree.txt 100
	./compiler testcase12.txt parse_tree.txt 100
	./compiler testcase13.txt parse_tree.txt 100
	
