#include "parser.c"
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

void time_calculate(char *prog_file, char *tree_file)
{
    clock_t start_time, end_time;

    double total_CPU_time, total_CPU_time_in_seconds;

    start_time = clock();

    printf("%p\n", prog_file);
    printf("%p\n", tree_file);

    run_parser(prog_file, tree_file);

    end_time = clock();

    total_CPU_time = (double)(end_time - start_time);

    total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;

    printf("Time taken by CPU:\n %f\n (in seconds): %f\n\n\n", total_CPU_time, total_CPU_time_in_seconds);
}

// 1: remove comments: remove_comment(FILE *fp, char string)
// 2: lexer
// 3: parser
// 4: time

int main(int argc, char **argv)
{
    BUFFER_SIZE = atoi(argv[3]);
    Buffer = (char *)malloc(sizeof(char) * BUFFER_SIZE);

    printf("Building Grammar (Populating symbols)...\n");
    build_grammar("../grammar.txt");

    while (true)
    {
        // printf(" ______________________________________________________________________________________________________________________________________\n");
        // printf("                                                                                                                                      |\n");
        printf("  0 : For exit                                                                                                                        \n");
        printf("  1 : For removal of comments                                                                                                         \n");
        printf("  2 : For printing the token list (on the console) generated by the lexer                                                             \n");
        printf("  3 : For parsing to verify the syntactic correctness of the input source code and printing the parse tree appropriately              \n");
        printf("  4 : For printing (on the console) the total time taken by our stage 1 code of lexer and parser to verify the syntactic correctness   \n");
        // printf("|______________________________________________________________________________________________________________________________________|\n\n");
        printf("Your input: ");

        int x = 0;
        scanf("%d", &x);

        printf("%d\n", x);

        FILE *fp = fopen(argv[1], "r");

        switch (x)
        {
        case 0:
        {
            printf("Thank you. Have a Good day ahead!\n");
            return 0;
        }
        case 1:
        {

            printf("Where do you want to store the uncommented code? (Input the name of the file with .txt): \n");

            // ------------------ Print the code on CONSOLE -------------------------
            char name[100];
            scanf("%s", name);
            removeComments(fp, name);
            break;
        }
        case 2:
        {

            printf("Where do you want to store the tokenized code?  (Input the name of the file with .txt): \n");
            // ------------------------ Print the tokenized code on the console --------------------------------
            char name[100];
            scanf("%s", name);
            test_lexer_run(argv[1], name);
            break;
        }
        case 3:
        {
            run_parser(argv[1], argv[2]);
            break;
        }
        case 4:
        {
            printf("%p\n", argv[1]);
            printf("%p\n", argv[2]);
            time_calculate(argv[1], argv[2]);
            // for(int i = 0; i <= 111; i++){
            //     printf("%s\n", grammar[i]);
            // }
            break;
        }

        default:
            printf("Wrong input");
            break;
        }
    }
}